package:
  name: ros-humble-launch-ros
  version: 0.19.3
source:
  git_url: https://github.com/ros2-gbp/launch_ros-release.git
  git_rev: release/humble/launch_ros/0.19.3-1
  folder: ros-humble-launch-ros/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - importlib-metadata
    - pytest
    - python
    - pyyaml
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-index-python
    - ros-humble-ament-pep257
    - ros-humble-composition-interfaces
    - ros-humble-launch
    - ros-humble-lifecycle-msgs
    - ros-humble-osrf-pycommon
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - setuptools
  run:
    - importlib-metadata
    - python
    - pyyaml
    - ros-humble-ament-index-python
    - ros-humble-composition-interfaces
    - ros-humble-launch
    - ros-humble-lifecycle-msgs
    - ros-humble-osrf-pycommon
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
