# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-rosidl-generator-py
  version: 0.14.4
source:
  git: https://github.com/ros2-gbp/rosidl_python-release.git
  rev: release/humble/rosidl_generator_py/0.14.4-1
  target_directory: ros-humble-rosidl-generator-py/src/work
  patches:
    - patch/ros-humble-rosidl-generator-py.patch

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-index-python
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-python-cmake-module
    - ros-humble-rmw
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-cmake
    - ros-humble-rosidl-generator-c
    - ros-humble-rosidl-generator-cpp
    - ros-humble-rosidl-parser
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-typesupport-c
    - ros-humble-rosidl-typesupport-fastrtps-c
    - ros-humble-rosidl-typesupport-interface
    - ros-humble-rosidl-typesupport-introspection-c
    - ros-humble-rpyutils
    - ros-humble-test-interface-files
    - ros2-distro-mutex 0.5 humble
  run:
    - numpy
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-index-python
    - ros-humble-python-cmake-module
    - ros-humble-rmw
    - ros-humble-ros-workspace
    - ros-humble-rosidl-cli
    - ros-humble-rosidl-cmake
    - ros-humble-rosidl-generator-c
    - ros-humble-rosidl-parser
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-typesupport-c
    - ros-humble-rosidl-typesupport-interface
    - ros-humble-rpyutils
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
