package:
  name: ros-humble-tf2-geometry-msgs
  version: 0.25.0
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/humble/tf2_geometry_msgs/0.25.0-2
  folder: ros-humble-tf2-geometry-msgs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-geometry-msgs
    - ros-humble-orocos-kdl-vendor
    - ros-humble-python-cmake-module
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-tf2
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.1 humble
  run:
    - numpy
    - python
    - ros-humble-geometry-msgs
    - ros-humble-orocos-kdl-vendor
    - ros-humble-ros-workspace
    - ros-humble-tf2
    - ros-humble-tf2-ros
    - ros-humble-tf2-ros-py
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
