# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-sros2-cmake
  version: 0.10.4
source:
  git: https://github.com/ros2-gbp/sros2-release.git
  rev: release/humble/sros2_cmake/0.10.4-2
  target_directory: ros-humble-sros2-cmake/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-test
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros-humble-sros2
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros-humble-sros2
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
