package:
  name: ros-humble-geometry2
  version: 0.25.0
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/humble/geometry2/0.25.0-2
  folder: ros-humble-geometry2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-tf2
    - ros-humble-tf2-bullet
    - ros-humble-tf2-eigen
    - ros-humble-tf2-eigen-kdl
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-kdl
    - ros-humble-tf2-msgs
    - ros-humble-tf2-py
    - ros-humble-tf2-ros
    - ros-humble-tf2-sensor-msgs
    - ros-humble-tf2-tools
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
