package:
  name: ros-humble-rmw-connextdds
  version: 0.11.1
source:
  git_url: https://github.com/ros2-gbp/rmw_connextdds-release.git
  git_rev: release/humble/rmw_connextdds/0.11.1-2
  folder: ros-humble-rmw-connextdds/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-rmw-connextdds-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-ament-cmake
    - ros-humble-rmw-connextdds-common
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
