package:
  name: ros-humble-robot-state-publisher
  version: 3.0.2
source:
  git_url: https://github.com/ros2-gbp/robot_state_publisher-release.git
  git_rev: release/humble/robot_state_publisher/3.0.2-2
  folder: ros-humble-robot-state-publisher/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-builtin-interfaces
    - ros-humble-geometry-msgs
    - ros-humble-kdl-parser
    - ros-humble-launch-ros
    - ros-humble-launch-testing-ament-cmake
    - ros-humble-orocos-kdl-vendor
    - ros-humble-rcl-interfaces
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-builtin-interfaces
    - ros-humble-geometry-msgs
    - ros-humble-kdl-parser
    - ros-humble-orocos-kdl-vendor
    - ros-humble-rcl-interfaces
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
