package:
  name: ros-humble-rosbag2-py
  version: 0.15.2
source:
  git_url: https://github.com/ros2-gbp/rosbag2-release.git
  git_rev: release/humble/rosbag2_py/0.15.2-1
  folder: ros-humble-rosbag2-py/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pybind11
  host:
    - pytest
    - python
    - ros-humble-ament-cmake-python
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-pybind11-vendor
    - ros-humble-python-cmake-module
    - ros-humble-rcl-interfaces
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosbag2-compression
    - ros-humble-rosbag2-cpp
    - ros-humble-rosbag2-storage
    - ros-humble-rosbag2-storage-default-plugins
    - ros-humble-rosbag2-transport
    - ros-humble-rosidl-runtime-py
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.1 humble
    - pybind11
  run:
    - python
    - ros-humble-pybind11-vendor
    - ros-humble-ros-workspace
    - ros-humble-rosbag2-compression
    - ros-humble-rosbag2-cpp
    - ros-humble-rosbag2-storage
    - ros-humble-rosbag2-transport
    - ros-humble-rpyutils
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
