package:
  name: ros-humble-rosidl-typesupport-cpp
  version: 2.0.0
source:
  git_url: https://github.com/ros2-gbp/rosidl_typesupport-release.git
  git_rev: release/humble/rosidl_typesupport_cpp/2.0.0-2
  folder: ros-humble-rosidl-typesupport-cpp/src/work
  patches:
    - patch/ros-humble-rosidl-typesupport-cpp.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake-core
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-performance-test-fixture
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-c
    - ros-humble-rosidl-typesupport-fastrtps-cpp
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-ament-cmake-core
    - ros-humble-ament-index-python
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-ros-workspace
    - ros-humble-rosidl-cli
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-c
    - ros-humble-rosidl-typesupport-fastrtps-cpp
    - ros-humble-rosidl-typesupport-interface
    - ros-humble-rosidl-typesupport-introspection-cpp
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
