# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-ros2launch
  version: 0.19.7
source:
  git: https://github.com/ros2-gbp/launch_ros-release.git
  rev: release/humble/ros2launch/0.19.7-2
  target_directory: ros-humble-ros2launch/src/work

build:
  script: ${{ 'build_ament_python.sh' if unix else 'bld_ament_python.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-index-python
    - ros-humble-ament-pep257
    - ros-humble-launch
    - ros-humble-launch-ros
    - ros-humble-launch-xml
    - ros-humble-launch-yaml
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros-humble-ros2pkg
    - ros2-distro-mutex 0.5 humble
    - setuptools
  run:
    - python
    - ros-humble-ament-index-python
    - ros-humble-launch
    - ros-humble-launch-ros
    - ros-humble-launch-xml
    - ros-humble-launch-yaml
    - ros-humble-ros-workspace
    - ros-humble-ros2cli
    - ros-humble-ros2pkg
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
