# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-rclpy
  version: 3.3.12
source:
  git: https://github.com/ros2-gbp/rclpy-release.git
  rev: release/humble/rclpy/3.3.12-1
  target_directory: ros-humble-rclpy/src/work
  patches:
    - patch/ros-humble-rclpy.osx.patch

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-pybind11-vendor
    - ros-humble-python-cmake-module
    - ros-humble-rcl
    - ros-humble-rcl-action
    - ros-humble-rcl-lifecycle
    - ros-humble-rcl-logging-interface
    - ros-humble-rcl-yaml-param-parser
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-rmw
    - ros-humble-rmw-implementation
    - ros-humble-rmw-implementation-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-generator-py
    - ros-humble-rosidl-runtime-c
    - ros-humble-test-msgs
    - ros-humble-unique-identifier-msgs
    - ros2-distro-mutex 0.5 humble
    - pybind11
  run:
    - python
    - ros-humble-ament-index-python
    - ros-humble-builtin-interfaces
    - ros-humble-rcl
    - ros-humble-rcl-action
    - ros-humble-rcl-interfaces
    - ros-humble-rcl-lifecycle
    - ros-humble-rcl-logging-interface
    - ros-humble-rcl-yaml-param-parser
    - ros-humble-rmw
    - ros-humble-rmw-implementation
    - ros-humble-ros-workspace
    - ros-humble-rosgraph-msgs
    - ros-humble-rosidl-runtime-c
    - ros-humble-rpyutils
    - ros-humble-unique-identifier-msgs
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
