package:
  name: ros-humble-ros-base
  version: 0.10.0
source:
  git_url: https://github.com/ros2-gbp/variants-release.git
  git_rev: release/humble/ros_base/0.10.0-1
  folder: ros-humble-ros-base/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-geometry2
    - ros-humble-kdl-parser
    - ros-humble-robot-state-publisher
    - ros-humble-ros-core
    - ros-humble-ros-workspace
    - ros-humble-rosbag2
    - ros-humble-urdf
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
