# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-ros2cli-common-extensions
  version: 0.1.1
source:
  git: https://github.com/ros2-gbp/ros2cli_common_extensions-release.git
  rev: release/humble/ros2cli_common_extensions/0.1.1-4
  target_directory: ros-humble-ros2cli-common-extensions/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-launch-xml
    - ros-humble-launch-yaml
    - ros-humble-ros-workspace
    - ros-humble-ros2action
    - ros-humble-ros2cli
    - ros-humble-ros2component
    - ros-humble-ros2doctor
    - ros-humble-ros2interface
    - ros-humble-ros2launch
    - ros-humble-ros2lifecycle
    - ros-humble-ros2multicast
    - ros-humble-ros2node
    - ros-humble-ros2param
    - ros-humble-ros2pkg
    - ros-humble-ros2run
    - ros-humble-ros2service
    - ros-humble-ros2topic
    - ros-humble-sros2
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
