# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-tf2-tools
  version: 0.25.6
source:
  git: https://github.com/ros2-gbp/geometry2-release.git
  rev: release/humble/tf2_tools/0.25.6-1
  target_directory: ros-humble-tf2-tools/src/work

build:
  script: ${{ 'build_ament_python.sh' if unix else 'bld_ament_python.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.5 humble
    - setuptools
  run:
    - graphviz
    - python
    - pyyaml
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-tf2-msgs
    - ros-humble-tf2-py
    - ros-humble-tf2-ros-py
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
