# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-rmw-fastrtps-cpp
  version: 6.2.6
source:
  git: https://github.com/ros2-gbp/rmw_fastrtps-release.git
  rev: release/humble/rmw_fastrtps_cpp/6.2.6-1
  target_directory: ros-humble-rmw-fastrtps-cpp/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 5
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-fastcdr
    - ros-humble-fastrtps
    - ros-humble-fastrtps-cmake-module
    - ros-humble-osrf-testing-tools-cpp
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-rmw
    - ros-humble-rmw-dds-common
    - ros-humble-rmw-fastrtps-shared-cpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-cmake
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-fastrtps-c
    - ros-humble-rosidl-typesupport-fastrtps-cpp
    - ros-humble-test-msgs
    - ros-humble-tracetools
    - ros2-distro-mutex 0.5 humble
  run:
    - python
    - ros-humble-ament-cmake
    - ros-humble-fastcdr
    - ros-humble-fastrtps
    - ros-humble-fastrtps-cmake-module
    - ros-humble-rcpputils
    - ros-humble-rcutils
    - ros-humble-rmw
    - ros-humble-rmw-dds-common
    - ros-humble-rmw-fastrtps-shared-cpp
    - ros-humble-ros-workspace
    - ros-humble-rosidl-cmake
    - ros-humble-rosidl-runtime-c
    - ros-humble-rosidl-runtime-cpp
    - ros-humble-rosidl-typesupport-fastrtps-c
    - ros-humble-rosidl-typesupport-fastrtps-cpp
    - ros-humble-tracetools
    - ros2-distro-mutex 0.5 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
