package:
  name: ros-humble-stereo-msgs
  version: 4.2.2
source:
  git_url: https://github.com/ros2-gbp/common_interfaces-release.git
  git_rev: release/humble/stereo_msgs/4.2.2-1
  folder: ros-humble-stereo-msgs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.1 humble
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
